[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "@uniswapContracts/=lib/v3-core/contracts/",
    "@uniswapPeriphery/=lib/v3-periphery/contracts/",
    
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
